FROM ubuntu:16.04
MAINTAINER Serhii Sokolov (sokolov.job@gmail.com)

RUN apt-get update -y && apt-get install -y python-xattr cmake automake autoconf libtool bison gcc g++ libboost-all-dev libboost-dev python libicu-dev openssl libssl-dev checkinstall \
apt-transport-https ca-certificates curl software-properties-common linux-image-extra-$(uname -r) linux-image-extra-virtual libprotobuf-dev protobuf-compiler pkg-config \
google-mock libgflags-dev libgtest-dev clang libc++-dev gdb mc

